#pragma once

#define SDHOST_CMD_NEW_FLAG      0x8000
#define SDHOST_CMD_FAIL_FLAG     0x4000
#define SDHOST_CMD_BUSYWAIT      0x800
#define SDHOST_CMD_NO_RESPONSE   0x400
#define SDHOST_CMD_LONG_RESPONSE 0x200
#define SDHOST_CMD_WRITE_CMD     0x80
#define SDHOST_CMD_READ_CMD      0x40
#define SDHOST_CMD_CMD_MASK      0x3f

#define SDHOST_CMD_BIT_NEW       15
#define SDHOST_CMD_BIT_FAIL      14
#define SDHOST_CMD_BIT_BUSYWAIT  11
#define SDHOST_CMD_BIT_NO_RESP   10
#define SDHOST_CMD_BIT_LONG_RESP 9
#define SDHOST_CMD_BIT_WRITE     7
#define SDHOST_CMD_BIT_READ      6
#define SDHOST_CMD_CMD_MASK      0x3f

#define SDHOST_CMD_HAS_DATA_MASK \
  (BIT(SDHOST_CMD_BIT_READ) | BIT(SDHOST_CMD_BIT_WRITE))

#define __SDHOST_CMD_GEN(__n, __wr, __rd, __long_resp, __no_resp, __busy_resp)\
  (((__n) & SDHOST_CMD_CMD_MASK) |\
  ((__wr) << SDHOST_CMD_BIT_WRITE) |\
  ((__rd) << SDHOST_CMD_BIT_READ) |\
  ((__long_resp) << SDHOST_CMD_BIT_LONG_RESP) |\
  ((__no_resp) << SDHOST_CMD_BIT_NO_RESP))

#define SDHOST_CMD_GEN(__n, __grp_0, __grp_1) \
  [__n] = __SDHOST_CMD_GEN(__n, __grp_0, __grp_1)

#define NO_RESP_NO 0
#define NO_RESP_YES 1

#define RD_NO 0
#define RD_YES 1

#define WR_NO 0
#define WR_YES 1

#define RESP_NORM 0, 0, 0
#define RESP_LONG 1, 0, 0
#define RESP_BUSY 0, 0, 1
#define RESP_NONE 0, 1, 0
#define DIR_NONE 0, 0
#define DIR_TO_CARD 1, 0
#define DIR_FROM_CARD 0, 1

static uint32_t sd_commands[] = {
  SDHOST_CMD_GEN(0,  DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(1,  DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(2,  DIR_NONE     , RESP_LONG),
  SDHOST_CMD_GEN(3,  DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(4,  DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(5,  DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(6,  DIR_FROM_CARD, RESP_NORM),
  SDHOST_CMD_GEN(7,  DIR_NONE     , RESP_BUSY),
  SDHOST_CMD_GEN(8,  DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(9,  DIR_NONE     , RESP_LONG),
  SDHOST_CMD_GEN(10, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(11, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(12, DIR_NONE     , RESP_BUSY),
  SDHOST_CMD_GEN(13, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(14, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(15, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(16, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(17, DIR_FROM_CARD, RESP_NORM),
  SDHOST_CMD_GEN(18, DIR_FROM_CARD, RESP_NORM),
  SDHOST_CMD_GEN(19, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(20, DIR_NONE     , RESP_BUSY),
  SDHOST_CMD_GEN(21, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(22, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(23, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(24, DIR_TO_CARD  , RESP_NORM),
  SDHOST_CMD_GEN(25, DIR_TO_CARD  , RESP_NORM),
  SDHOST_CMD_GEN(26, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(27, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(28, DIR_NONE     , RESP_BUSY),
  SDHOST_CMD_GEN(29, DIR_NONE     , RESP_BUSY),
  SDHOST_CMD_GEN(30, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(31, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(32, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(33, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(34, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(35, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(36, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(37, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(38, DIR_NONE     , RESP_BUSY),
  SDHOST_CMD_GEN(39, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(40, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(41, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(42, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(43, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(44, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(45, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(46, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(47, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(48, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(49, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(50, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(51, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(52, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(53, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(54, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(55, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(56, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(57, DIR_NONE     , RESP_NONE),
  SDHOST_CMD_GEN(58, DIR_NONE     , RESP_NORM),
  SDHOST_CMD_GEN(59, DIR_NONE     , RESP_NONE)
};

static uint32_t sd_acommands[] = {
  SDHOST_CMD_GEN(0, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(1, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(2, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(3, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(4, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(5, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(6, DIR_NONE, RESP_NORM),
  SDHOST_CMD_GEN(7, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(8, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(9, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(10, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(11, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(12, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(13, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(14, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(15, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(16, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(17, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(18, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(19, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(20, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(21, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(22, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(23, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(24, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(25, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(26, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(27, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(28, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(29, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(30, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(31, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(32, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(33, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(34, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(35, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(36, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(37, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(38, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(39, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(40, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(41, DIR_NONE, RESP_NORM),
  SDHOST_CMD_GEN(42, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(43, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(44, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(45, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(46, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(47, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(48, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(49, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(50, DIR_NONE, RESP_NORM),
  SDHOST_CMD_GEN(51, DIR_FROM_CARD, RESP_NORM),
  SDHOST_CMD_GEN(52, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(53, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(54, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(55, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(56, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(57, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(58, DIR_NONE, RESP_NONE),
  SDHOST_CMD_GEN(59, DIR_NONE, RESP_NONE)
};
