#pragma once
#include <memory_map.h>
#include <stdint.h>
#include <stdbool.h>
#include <ioreg.h>

#define DMA_BASE (unsigned long long)(BCM2835_MEM_PERIPH_BASE + 0x00007000)
#define DMA_CH_BASE(channel)               (DMA_BASE + channel * 0x100)
#define DMA_CS(channel)          (ioreg32_t)(DMA_CH_BASE(channel) + 0x00)
#define DMA_CONBLK_AD(channel)   (ioreg32_t)(DMA_CH_BASE(channel) + 0x04)
#define DMA_TI(channel)          (ioreg32_t)(DMA_CH_BASE(channel) + 0x08)
#define DMA_SOURCE_AD(channel)   (ioreg32_t)(DMA_CH_BASE(channel) + 0x0c)
#define DMA_DEST_AD(channel)     (ioreg32_t)(DMA_CH_BASE(channel) + 0x10)
#define DMA_TXFR_LEN(channel)    (ioreg32_t)(DMA_CH_BASE(channel) + 0x14)
#define DMA_STRIDE(channel)      (ioreg32_t)(DMA_CH_BASE(channel) + 0x18)
#define DMA_NEXT_CONBLK(channel) (ioreg32_t)(DMA_CH_BASE(channel) + 0x1c)
#define DMA_DEBUG(channel)       (ioreg32_t)(DMA_CH_BASE(channel) + 0x20)
#define DMA_ENABLE               (ioreg32_t)(DMA_BASE + 0xff0)

#define DMA_CS_ACTIVE                         (1 <<  0)
#define DMA_CS_END                            (1 <<  1)
#define DMA_CS_INT                            (1 <<  2)
#define DMA_CS_DREQ                           (1 <<  3)
#define DMA_CS_PAUSED                         (1 <<  4)
#define DMA_CS_DREQ_STOPS_DMA                 (1 <<  5)
#define DMA_CS_WAITING_FOR_OUTSTANDING_WRITES (1 <<  6)
#define DMA_CS_ERROR                          (1 <<  8)
#define DMA_CS_PRIORITY(x)            ((x & 0xf) << 16)
#define DMA_CS_PANIC_PRIORITY(x)      ((x & 0xf) << 20)
#define DMA_CS_WAIT_FOR_OUTSTANDING_WRITES    (1 << 28)
#define DMA_CS_DISDEBUG                       (1 << 29)
#define DMA_CS_ABORT                          (1 << 30)
#define DMA_CS_RESET                          (1 << 31)


#define DMA_TI_INTEN                   (1 <<  0)
#define DMA_TI_TD_MODE                 (1 <<  1)
#define DMA_TI_WAIT_RESP               (1 <<  3)
#define DMA_TI_DEST_INC                (1 <<  4)
#define DMA_TI_DEST_WIDTH              (1 <<  5)
#define DMA_TI_DEST_DREQ               (1 <<  6)
#define DMA_TI_DEST_IGNORE             (1 <<  7)
#define DMA_TI_SRC_INC                 (1 <<  8)
#define DMA_TI_SRC_WIDTH               (1 <<  9)
#define DMA_TI_SRC_DREQ                (1 << 10)
#define DMA_TI_SRC_IGNORE              (1 << 11)
#define DMA_TI_BURST_LENGTH   ((x & 0x0f) << 12)
#define DMA_TI_PERMAP(x)      ((x & 0x1f) << 16)
#define DMA_TI_WAITS(x)       ((x & 0x1f) << 25)
#define DMA_TI_NO_WIDE_BURSTS          (1 << 26)

#define DMA_TXFR_LEN_XLENGTH(x) ((x & 0xffff) <<  0)
#define DMA_TXFR_LEN_YLENGTH(x) ((x & 0x3fff) << 16)

#define DMA_STRIDE_D_STRIDE(x) ((x & 0xffff) << 16)
#define DMA_STRIDE_S_STRIDE(x) ((x & 0xffff) <<  0)

#define DMA_DEBUG_READ_LAST_NOT_SET_ERROR (1 <<  0)
#define DMA_DEBUG_FIFO_ERROR              (1 <<  1)
#define DMA_DEBUG_READ_ERROR              (1 <<  2)
#define DMA_DEBUG_OUTSTANDING_WRITES    (0xf <<  4)
#define DMA_DEBUG_DMA_ID            (0xffff  <<  8)
#define DMA_DEBUG_DMA_STATE         (0x1ffff << 16)
#define DMA_DEBUG_VERSION                 (7 << 27)
#define DMA_DEBUG_LITE                    (1 << 28)
